SELECT *
FROM(
  SELECT
    (
    CASE
      WHEN aff_track ILIKE '%afghanistan%'  THEN 'afghanistan'
      WHEN aff_track ILIKE '%albania%'  THEN 'albania'
      WHEN aff_track ILIKE '%algeria%'  THEN 'algeria'
      WHEN aff_track ILIKE '%american samoa%'  THEN 'american samoa'
      WHEN aff_track ILIKE '%AS\_EN%'  THEN 'american samoa'
      WHEN aff_track ILIKE '%andorra%'  THEN 'andorra'
      WHEN aff_track ILIKE '%angola%'  THEN 'angola'
      WHEN aff_track ILIKE '%antarctica%'  THEN 'antarctica'
      WHEN aff_track ILIKE '%antigua and barbuda%'  THEN 'antigua and barbuda'
      WHEN aff_track ILIKE '%argentina%'  THEN 'argentina'
      WHEN aff_track ILIKE '%AR\_ES%'  THEN 'argentina'
      WHEN aff_track ILIKE '%armenia%'  THEN 'armenia'
      WHEN aff_track ILIKE '%australia%'  THEN 'australia'
      WHEN aff_track ILIKE '%austria%'  THEN 'austria'
      WHEN aff_track ILIKE '%azerbaijan%'  THEN 'azerbaijan'
      WHEN aff_track ILIKE '%bahrain%'  THEN 'bahrain'
      WHEN aff_track ILIKE '%bangladesh%'  THEN 'bangladesh'
      WHEN aff_track ILIKE '%barbados%'  THEN 'barbados'
      WHEN aff_track ILIKE '%belarus%'  THEN 'belarus'
      WHEN aff_track ILIKE '%belgium%'  THEN 'belgium'
      WHEN aff_track ILIKE '%belize%'  THEN 'belize'
      WHEN aff_track ILIKE '%benin%'  THEN 'benin'
      WHEN aff_track ILIKE '%bhutan%'  THEN 'bhutan'
      WHEN aff_track ILIKE '%bolivia%'  THEN 'bolivia'
      WHEN aff_track ILIKE '%bosnia and herzegovina%'  THEN 'bosnia and herzegovina'
      WHEN aff_track ILIKE '%botswana%'  THEN 'botswana'
      WHEN aff_track ILIKE '%brazil%'  THEN 'brazil'
      WHEN aff_track ILIKE '%brunei%'  THEN 'brunei'
      WHEN aff_track ILIKE '%bulgaria%'  THEN 'bulgaria'
      WHEN aff_track ILIKE '%burkina faso%'  THEN 'burkina faso'
      WHEN aff_track ILIKE '%burundi%'  THEN 'burundi'
      WHEN aff_track ILIKE '%cambodia%'  THEN 'cambodia'
      WHEN aff_track ILIKE '%cameroon%'  THEN 'cameroon'
      WHEN aff_track ILIKE '%canada%'  THEN 'canada'
      WHEN aff_track ILIKE '%cape verde%'  THEN 'cape verde'
      WHEN aff_track ILIKE '%central african republic%'  THEN 'central african republic'
      WHEN aff_track ILIKE '%chad%'  THEN 'chad'
      WHEN aff_track ILIKE '%chile%'  THEN 'chile'
      WHEN aff_track ILIKE '%china%'  THEN 'china'
      WHEN aff_track ILIKE '%ALL-CHI%'  THEN 'china'
      WHEN aff_track ILIKE '%christmas island%'  THEN 'christmas island'
      WHEN aff_track ILIKE '%cocos (keeling) islands%'  THEN 'cocos (keeling) islands'
      WHEN aff_track ILIKE '%colombia%'  THEN 'colombia'
      WHEN aff_track ILIKE '%comoros%'  THEN 'comoros'
      WHEN aff_track ILIKE '%cook islands%'  THEN 'cook islands'
      WHEN aff_track ILIKE '%costa rica%'  THEN 'costa rica'
      WHEN aff_track ILIKE '%cote divoire%'  THEN 'cote divoire'
      WHEN aff_track ILIKE '%croatia%'  THEN 'croatia'
      WHEN aff_track ILIKE '%cyprus%'  THEN 'cyprus'
      WHEN aff_track ILIKE '%czech republic%'  THEN 'czech republic'
      WHEN aff_track ILIKE '%democratic republic of the congo%'  THEN 'democratic republic of the congo'
      WHEN aff_track ILIKE '%denmark%'  THEN 'denmark'
      WHEN aff_track ILIKE '%djibouti%'  THEN 'djibouti'
      WHEN aff_track ILIKE '%dominica%'  THEN 'dominica'
      WHEN aff_track ILIKE '%dominican republic%'  THEN 'dominican republic'
      WHEN aff_track ILIKE '%ecuador%'  THEN 'ecuador'
      WHEN aff_track ILIKE '%egypt%'  THEN 'egypt'
      WHEN aff_track ILIKE '%el salvador%'  THEN 'el salvador'
      WHEN aff_track ILIKE '%equatorial guinea%'  THEN 'equatorial guinea'
      WHEN aff_track ILIKE '%eritrea%'  THEN 'eritrea'
      WHEN aff_track ILIKE '%estonia%'  THEN 'estonia'
      WHEN aff_track ILIKE '%ethiopia%'  THEN 'ethiopia'
      WHEN aff_track ILIKE '%federated states of micronesia%'  THEN 'federated states of micronesia'
      WHEN aff_track ILIKE '%fiji%'  THEN 'fiji'
      WHEN aff_track ILIKE '%finland%'  THEN 'finland'
      WHEN aff_track ILIKE '%france%'  THEN 'france'
      WHEN aff_track ILIKE '%french polynesia%'  THEN 'french polynesia'
      WHEN aff_track ILIKE '%french southern and antarctic lands%'  THEN 'french southern and antarctic lands'
      WHEN aff_track ILIKE '%gabon%'  THEN 'gabon'
      WHEN aff_track ILIKE '%georgia%'  THEN 'georgia'
      WHEN aff_track ILIKE '%germany%'  THEN 'germany'
      WHEN aff_track ILIKE '%ghana%'  THEN 'ghana'
      WHEN aff_track ILIKE '%greece%'  THEN 'greece'
      WHEN aff_track ILIKE '%grenada%'  THEN 'grenada'
      WHEN aff_track ILIKE '%guam%'  THEN 'guam'
      WHEN aff_track ILIKE '%guatemala%'  THEN 'guatemala'
      WHEN aff_track ILIKE '%guernsey%'  THEN 'guernsey'
      WHEN aff_track ILIKE '%guinea%'  THEN 'guinea'
      WHEN aff_track ILIKE '%guinea-bissau%'  THEN 'guinea-bissau'
      WHEN aff_track ILIKE '%guyana%'  THEN 'guyana'
      WHEN aff_track ILIKE '%haiti%'  THEN 'haiti'
      WHEN aff_track ILIKE '%heard island and mcdonald islands%'  THEN 'heard island and mcdonald islands'
      WHEN aff_track ILIKE '%honduras%'  THEN 'honduras'
      WHEN aff_track ILIKE '%hungary%'  THEN 'hungary'
      WHEN aff_track ILIKE '%iceland%'  THEN 'iceland'
      WHEN aff_track ILIKE '%india%'  THEN 'india'
      WHEN aff_track ILIKE '%indonesia%'  THEN 'indonesia'
      WHEN aff_track ILIKE '%iraq%'  THEN 'iraq'
      WHEN aff_track ILIKE '%ireland%'  THEN 'ireland'
      WHEN aff_track ILIKE '%israel%'  THEN 'israel'
      WHEN aff_track ILIKE '%italy%'  THEN 'italy'
      WHEN aff_track ILIKE '%jamaica%'  THEN 'jamaica'
      WHEN aff_track ILIKE '%japan%'  THEN 'japan'
      WHEN aff_track ILIKE '%jersey%'  THEN 'jersey'
      WHEN aff_track ILIKE '%jordan%'  THEN 'jordan'
      WHEN aff_track ILIKE '%kazakhstan%'  THEN 'kazakhstan'
      WHEN aff_track ILIKE '%kenya%'  THEN 'kenya'
      WHEN aff_track ILIKE '%kiribati%'  THEN 'kiribati'
      WHEN aff_track ILIKE '%kuwait%'  THEN 'kuwait'
      WHEN aff_track ILIKE '%kyrgyzstan%'  THEN 'kyrgyzstan'
      WHEN aff_track ILIKE '%laos%'  THEN 'laos'
      WHEN aff_track ILIKE '%latvia%'  THEN 'latvia'
      WHEN aff_track ILIKE '%lebanon%'  THEN 'lebanon'
      WHEN aff_track ILIKE '%lesotho%'  THEN 'lesotho'
      WHEN aff_track ILIKE '%liberia%'  THEN 'liberia'
      WHEN aff_track ILIKE '%libya%'  THEN 'libya'
      WHEN aff_track ILIKE '%liechtenstein%'  THEN 'liechtenstein'
      WHEN aff_track ILIKE '%lithuania%'  THEN 'lithuania'
      WHEN aff_track ILIKE '%luxembourg%'  THEN 'luxembourg'
      WHEN aff_track ILIKE '%macedonia (fyrom)%'  THEN 'macedonia (fyrom)'
      WHEN aff_track ILIKE '%madagascar%'  THEN 'madagascar'
      WHEN aff_track ILIKE '%malawi%'  THEN 'malawi'
      WHEN aff_track ILIKE '%malaysia%'  THEN 'malaysia'
      WHEN aff_track ILIKE '%maldives%'  THEN 'maldives'
      WHEN aff_track ILIKE '%mali%'  THEN 'mali'
      WHEN aff_track ILIKE '%malta%'  THEN 'malta'
      WHEN aff_track ILIKE '%marshall islands%'  THEN 'marshall islands'
      WHEN aff_track ILIKE '%mauritania%'  THEN 'mauritania'
      WHEN aff_track ILIKE '%mauritius%'  THEN 'mauritius'
      WHEN aff_track ILIKE '%mexico%'  THEN 'mexico'
      WHEN aff_track ILIKE '%moldova%'  THEN 'moldova'
      WHEN aff_track ILIKE '%monaco%'  THEN 'monaco'
      WHEN aff_track ILIKE '%mongolia%'  THEN 'mongolia'
      WHEN aff_track ILIKE '%montenegro%'  THEN 'montenegro'
      WHEN aff_track ILIKE '%morocco%'  THEN 'morocco'
      WHEN aff_track ILIKE '%mozambique%'  THEN 'mozambique'
      WHEN aff_track ILIKE '%myanmar (burma)%'  THEN 'myanmar (burma)'
      WHEN aff_track ILIKE '%namibia%'  THEN 'namibia'
      WHEN aff_track ILIKE '%nauru%'  THEN 'nauru'
      WHEN aff_track ILIKE '%nepal%'  THEN 'nepal'
      WHEN aff_track ILIKE '%netherlands%'  THEN 'netherlands'
      WHEN aff_track ILIKE '%new caledonia%'  THEN 'new caledonia'
      WHEN aff_track ILIKE '%new zealand%'  THEN 'new zealand'
      WHEN aff_track ILIKE '%nicaragua%'  THEN 'nicaragua'
      WHEN aff_track ILIKE '%niger%'  THEN 'niger'
      WHEN aff_track ILIKE '%nigeria%'  THEN 'nigeria'
      WHEN aff_track ILIKE '%niue%'  THEN 'niue'
      WHEN aff_track ILIKE '%norfolk island%'  THEN 'norfolk island'
      WHEN aff_track ILIKE '%northern mariana islands%'  THEN 'northern mariana islands'
      WHEN aff_track ILIKE '%norway%'  THEN 'norway'
      WHEN aff_track ILIKE '%oman%'  THEN 'oman'
      WHEN aff_track ILIKE '%pakistan%'  THEN 'pakistan'
      WHEN aff_track ILIKE '%palau%'  THEN 'palau'
      WHEN aff_track ILIKE '%panama%'  THEN 'panama'
      WHEN aff_track ILIKE '%papua new guinea%'  THEN 'papua new guinea'
      WHEN aff_track ILIKE '%paraguay%'  THEN 'paraguay'
      WHEN aff_track ILIKE '%peru%'  THEN 'peru'
      WHEN aff_track ILIKE '%PE\_ES%'  THEN 'peru'
      WHEN aff_track ILIKE '%philippines%'  THEN 'philippines'
      WHEN aff_track ILIKE '%pitcairn islands%'  THEN 'pitcairn islands'
      WHEN aff_track ILIKE '%poland%'  THEN 'poland'
      WHEN aff_track ILIKE '%portugal%'  THEN 'portugal'
      WHEN aff_track ILIKE '%qatar%'  THEN 'qatar'
      WHEN aff_track ILIKE '%republic of the congo%'  THEN 'republic of the congo'
      WHEN aff_track ILIKE '%romania%'  THEN 'romania'
      WHEN aff_track ILIKE '%russia%'  THEN 'russia'
      WHEN aff_track ILIKE '%rwanda%'  THEN 'rwanda'
      WHEN aff_track ILIKE '%saint helena, ascension and tristan da cunha%'  THEN 'saint helena, ascension and tristan da cunha'
      WHEN aff_track ILIKE '%saint kitts and nevis%'  THEN 'saint kitts and nevis'
      WHEN aff_track ILIKE '%saint lucia%'  THEN 'saint lucia'
      WHEN aff_track ILIKE '%saint pierre and miquelon%'  THEN 'saint pierre and miquelon'
      WHEN aff_track ILIKE '%saint vincent and the grenadines%'  THEN 'saint vincent and the grenadines'
      WHEN aff_track ILIKE '%samoa%'  THEN 'samoa'
      WHEN aff_track ILIKE '%san marino%'  THEN 'san marino'
      WHEN aff_track ILIKE '%sao tome and principe%'  THEN 'sao tome and principe'
      WHEN aff_track ILIKE '%saudi arabia%'  THEN 'saudi arabia'
      WHEN aff_track ILIKE '%senegal%'  THEN 'senegal'
      WHEN aff_track ILIKE '%serbia%'  THEN 'serbia'
      WHEN aff_track ILIKE '%seychelles%'  THEN 'seychelles'
      WHEN aff_track ILIKE '%sierra leone%'  THEN 'sierra leone'
      WHEN aff_track ILIKE '%singapore%'  THEN 'singapore'
      WHEN aff_track ILIKE '%slovakia%'  THEN 'slovakia'
      WHEN aff_track ILIKE '%slovenia%'  THEN 'slovenia'
      WHEN aff_track ILIKE '%solomon islands%'  THEN 'solomon islands'
      WHEN aff_track ILIKE '%somalia%'  THEN 'somalia'
      WHEN aff_track ILIKE '%south africa%'  THEN 'south africa'
      WHEN aff_track ILIKE '%south georgia and the south sandwich islands%' THEN 'south georgia and the south sandwich islands'
      WHEN aff_track ILIKE '%south korea%'  THEN 'south korea'
      WHEN aff_track ILIKE '%spain%'  THEN 'spain'
      WHEN aff_track ILIKE '%sri lanka%'  THEN 'sri lanka'
      WHEN aff_track ILIKE '%suriname%'  THEN 'suriname'
      WHEN aff_track ILIKE '%swaziland%'  THEN 'swaziland'
      WHEN aff_track ILIKE '%sweden%'  THEN 'sweden'
      WHEN aff_track ILIKE '%switzerland%'  THEN 'switzerland'
      WHEN aff_track ILIKE '%tajikistan%'  THEN 'tajikistan'
      WHEN aff_track ILIKE '%tanzania%'  THEN 'tanzania'
      WHEN aff_track ILIKE '%thailand%'  THEN 'thailand'
      WHEN aff_track ILIKE '%the bahamas%'  THEN 'the bahamas'
      WHEN aff_track ILIKE '%the gambia%'  THEN 'the gambia'
      WHEN aff_track ILIKE '%timor-leste%'  THEN 'timor-leste'
      WHEN aff_track ILIKE '%togo%'  THEN 'togo'
      WHEN aff_track ILIKE '%tokelau%'  THEN 'tokelau'
      WHEN aff_track ILIKE '%tonga%'  THEN 'tonga'
      WHEN aff_track ILIKE '%trinidad and tobago%'  THEN 'trinidad and tobago'
      WHEN aff_track ILIKE '%tunisia%'  THEN 'tunisia'
      WHEN aff_track ILIKE '%turkey%'  THEN 'turkey'
      WHEN aff_track ILIKE '%turkmenistan%'  THEN 'turkmenistan'
      WHEN aff_track ILIKE '%tuvalu%'  THEN 'tuvalu'
      WHEN aff_track ILIKE '%uganda%'  THEN 'uganda'
      WHEN aff_track ILIKE '%ukraine%'  THEN 'ukraine'
      WHEN aff_track ILIKE '%united arab emirates%'  THEN 'UAE'
      WHEN aff_track ILIKE '%united kingdom%'  THEN 'united kingdom'
      WHEN aff_track ILIKE '%united states%'  THEN 'united states'
      WHEN aff_track ILIKE '%united states minor outlying islands%'  THEN 'united states minor outlying islands'
      WHEN aff_track ILIKE '%uruguay%'  THEN 'uruguay'
      WHEN aff_track ILIKE '%uzbekistan%'  THEN 'uzbekistan'
      WHEN aff_track ILIKE '%vanuatu%'  THEN 'vanuatu'
      WHEN aff_track ILIKE '%vatican city%'  THEN 'vatican city'
      WHEN aff_track ILIKE '%venezuela%'  THEN 'venezuela'
      WHEN aff_track ILIKE '%vietnam%'  THEN 'vietnam'
      WHEN aff_track ILIKE '%wallis and futuna%'  THEN 'wallis and futuna'
      WHEN aff_track ILIKE '%yemen%'  THEN 'yemen'
      WHEN aff_track ILIKE '%zambia%'  THEN 'zambia'
      WHEN aff_track ILIKE '%zimbabwe%'  THEN 'zimbabwe'
      WHEN aff_track ILIKE '%hong kong%'  THEN 'Hong Kong'
      WHEN aff_track ILIKE '%Luxemburg%'  THEN 'Luxemburg'
      WHEN aff_track ILIKE '%uae%'  THEN 'UAE'
      WHEN aff_track ILIKE '%Macao%'  THEN 'macao'
      WHEN aff_track ILIKE '%Taiwan%'  THEN 'Taiwan'
      WHEN aff_track ILIKE '%South-Africa%'  THEN 'South-Africa'
      WHEN aff_track ILIKE '%Sri-Lanka%'  THEN 'Sri-Lanka'
      WHEN aff_track ILIKE '%Czech-Republic%'  THEN 'Czech-Republic'
      WHEN aff_track ILIKE '%South-Korea%'  THEN 'south-korea'
      WHEN aff_track ILIKE '%\_UK\_%'  THEN 'united kingdom'
      WHEN aff_track ILIKE '%\_UK\-%'  THEN 'united kingdom'
      WHEN aff_track ILIKE '%EN\_GB%'  THEN 'united kingdom'
      WHEN aff_track ILIKE '%EU-DE%'  THEN 'germany'
      WHEN aff_track ILIKE '%\_DE%'  THEN 'germany'
      WHEN aff_track ILIKE '%EU-ES%'  THEN 'spain'
      WHEN aff_track ILIKE '%CO\_ES%'  THEN 'spain'
      WHEN aff_track ILIKE '%EU-IT%'  THEN 'italy'
      WHEN aff_track ILIKE '%IT-IT%'  THEN 'italy'
      WHEN aff_track ILIKE '%IT\_IT%'  THEN 'italy'
      WHEN aff_track ILIKE '%BR-PT%'  THEN 'brazil'
      WHEN aff_track ILIKE '%BR\_PT%'  THEN 'brazil'
      WHEN aff_track ILIKE '%BR\_BR%'  THEN 'brazil'
      WHEN aff_track ILIKE '%MX-ES%'  THEN 'mexico'
      WHEN aff_track ILIKE '%MX\_ES%'  THEN 'mexico'
      WHEN aff_track ILIKE '%PT-PT%'  THEN 'portugal'
      WHEN aff_track ILIKE '%GLOBAL-PT%'  THEN 'portugal'
      WHEN aff_track ILIKE '%CO-ES%'  THEN 'colombia'
      WHEN aff_track ILIKE '%CO\_ES%'  THEN 'colombia'
      WHEN aff_track ILIKE '%CIS%'  THEN 'CIS'
      WHEN aff_track ILIKE '%SNG_RU%'  THEN 'CIS'
      WHEN aff_track ILIKE '%LATAM-ES%'  THEN 'Latin America'
      WHEN aff_track ILIKE '%Latam\_ES%'  THEN 'Latin America'
      WHEN aff_track ILIKE '%LA_ES%'  THEN 'Latin America'
      WHEN aff_track ILIKE '%LATAM%'  THEN 'Latin America'
      WHEN aff_track ILIKE '%EU-EN%'  THEN 'European Union'
      WHEN aff_track ILIKE '%Global-EN%'  THEN 'Global world (EN)'
      WHEN aff_track ILIKE '%ZA-EN%'  THEN 'South Africa'
      WHEN aff_track ILIKE '%West-Africa%'  THEN 'West Africa'
      WHEN aff_track ILIKE '%DE-DE%'  THEN 'germany'
      WHEN aff_track ILIKE '%SG-EN%'  THEN 'singapore'
      WHEN aff_track ILIKE '%AE-EN%'  THEN 'UAE'
      WHEN aff_track ILIKE '%AE-EN%'  THEN 'UAE'
      WHEN aff_track ILIKE '%CH-DE%'  THEN 'switzerland'
      WHEN aff_track ILIKE '%MDweb__All_ENG%'  THEN 'MDweb All ENG'
      WHEN aff_track ILIKE '%ALL-ENG-%'  THEN 'All ENG'
      WHEN aff_track ILIKE '%MDweb\_\_All_RU%'  THEN 'All RU'
      WHEN aff_track ILIKE '%\_ru\_%'  THEN 'All RU'
      WHEN aff_track ILIKE '%FR-FR%'  THEN 'france'
      WHEN aff_track ILIKE '%EU-FR%'  THEN 'france'
      WHEN aff_track ILIKE '%NL-NL%'  THEN 'netherlands'
      WHEN aff_track ILIKE '%ID-EN%'  THEN 'indonesia'
      WHEN aff_track ILIKE '%AT-DE%'  THEN 'austria'
      WHEN aff_track ILIKE '%NZ-EN%'  THEN 'new zealand'
      WHEN aff_track ILIKE '%\_NZ-%'  THEN 'new zealand'
      WHEN aff_track ILIKE '%\_NZ\_%'  THEN 'new zealand'
      WHEN aff_track ILIKE '%DK\_DK%'  THEN 'denmark'
      WHEN aff_track ILIKE '%IN\_BO%'  THEN 'bolivia'
      WHEN aff_track ILIKE '%MR\_BO%'  THEN 'mauritania'
      WHEN aff_track ILIKE '%MR-FR_BO%'  THEN 'mauritania'
      WHEN aff_track ILIKE '%MR_IQ%'  THEN 'mauritania'
      WHEN aff_track ILIKE '%MR-FR%'  THEN 'mauritania'
      WHEN aff_track ILIKE '%\_MY\_%'  THEN 'malaysia'
      WHEN aff_track ILIKE '%\_NL\_%'  THEN 'netherlands'
      WHEN aff_track ILIKE '%\_PH\_%'  THEN 'philippines'
      WHEN aff_track ILIKE '%\_PK\_%'  THEN 'pakistan'
      WHEN aff_track ILIKE '%\_PL\_%'  THEN 'poland'
      WHEN aff_track ILIKE '%PL-PL%'  THEN 'poland'
      WHEN aff_track ILIKE '%\_QA\_%'  THEN 'qatar'
      WHEN aff_track ILIKE '%\_SA\_%'  THEN 'south africa'
      WHEN aff_track ILIKE '%\_SE\_%'  THEN 'sweden'
      WHEN aff_track ILIKE '%\_SG\_%'  THEN 'singapore'
      WHEN aff_track ILIKE '%\_SIN-%'  THEN 'singapore'
      WHEN aff_track ILIKE '%\_SI\_%'  THEN 'slovenia'
      WHEN aff_track ILIKE '%\_ZA\_%'  THEN 'south africa'
      WHEN aff_track ILIKE '%\_TW\_%'  THEN 'taiwan'
      WHEN aff_track ILIKE '%\_TH\_%'  THEN 'thailand'
      WHEN aff_track ILIKE '%\_THAI\_%'  THEN 'thailand'
      WHEN aff_track ILIKE '%\_AE\_%'  THEN 'UAE'
      WHEN aff_track ILIKE '%\_ALL-FR\_%'  THEN 'ALL FR'
      WHEN aff_track ILIKE '%\_AT\_%'  THEN 'austria'
      WHEN aff_track ILIKE '%\_AT-%'  THEN 'austria'
      WHEN aff_track ILIKE '%\_BN\_%'  THEN 'brunei'
      WHEN aff_track ILIKE '%\_CAD\_%'  THEN 'canada'
      WHEN aff_track ILIKE '%\_CAD-%'  THEN 'canada'
      WHEN aff_track ILIKE '%\_CZ\_%'  THEN 'switzerland'
      WHEN aff_track ILIKE '%\_CZ-%'  THEN 'switzerland'
      WHEN aff_track ILIKE '%\_DK\_%'  THEN 'denmark'
      WHEN aff_track ILIKE '%SWISS%'  THEN 'switzerland'
      WHEN aff_track ILIKE '%SL-SL%'  THEN 'sierra leone'
      WHEN aff_track ILIKE '%\_KW\_%'  THEN 'kuwait'
      WHEN aff_track ILIKE '%\_IN\_%'  THEN 'india'
      WHEN aff_track ILIKE '%\_GER\_%'  THEN 'ALL GER'
      WHEN aff_track ILIKE '%\_S\_ENG\_%'  THEN 'ALL EN'
      WHEN aff_track ILIKE '%\_CH\_%'  THEN 'switzerland'
      WHEN aff_track ILIKE '%\_CN\_%'  THEN 'china'
      WHEN aff_track ILIKE '%\_IL\_%'  THEN 'israel'
      WHEN aff_track ILIKE '%\_VM\_%'  THEN 'vietnam'
      WHEN aff_track ILIKE '%\_NOR\_%'  THEN 'norway'
      WHEN aff_track ILIKE '%\_HK\_%'  THEN 'Hong Kong'
      WHEN aff_track ILIKE '%\_HK-%'  THEN 'Hong Kong'
      WHEN aff_track ILIKE '%\_PT\_%'  THEN 'portugal'
      WHEN aff_track ILIKE '%PT\_PT%'  THEN 'portugal'
      WHEN aff_track ILIKE '%KR\_0R%'  THEN 'south korea'
      WHEN aff_track ILIKE '%KR-KR%'  THEN 'south korea'
    END) AS country_name,
    aff_track
  FROM
    bogdan_temp_unique_aff_tracks) AS blabla
WHERE country_name ISNULL
